// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB_VQtg0ocLP_NKUMR1hYH0bHDZWJWQSy8',
    appId: '1:123189347991:web:f26951c5c9700784334bd2',
    messagingSenderId: '123189347991',
    projectId: 'live-stream-app-fb97f',
    authDomain: 'live-stream-app-fb97f.firebaseapp.com',
    storageBucket: 'live-stream-app-fb97f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZr1tm0ZGn-XwQqGPZ3sJ55lSBQxv2dKs',
    appId: '1:123189347991:android:e0928f9609720ddf334bd2',
    messagingSenderId: '123189347991',
    projectId: 'live-stream-app-fb97f',
    storageBucket: 'live-stream-app-fb97f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2cE7MiQMgLyBp6W7TW0hiCL-yBUS6xJU',
    appId: '1:123189347991:ios:9384e807d4f1ec55334bd2',
    messagingSenderId: '123189347991',
    projectId: 'live-stream-app-fb97f',
    storageBucket: 'live-stream-app-fb97f.appspot.com',
    iosBundleId: 'com.example.liveStreamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2cE7MiQMgLyBp6W7TW0hiCL-yBUS6xJU',
    appId: '1:123189347991:ios:9384e807d4f1ec55334bd2',
    messagingSenderId: '123189347991',
    projectId: 'live-stream-app-fb97f',
    storageBucket: 'live-stream-app-fb97f.appspot.com',
    iosBundleId: 'com.example.liveStreamApp',
  );
}
